@Alegeus.Hackaton.PlanAssistance_HostAddress = http://localhost:59029

GET {{Alegeus.Hackaton.PlanAssistance_HostAddress}}/weatherforecast/
Accept: application/json

###
POST http://localhost:59029/wca-chat
Content-Type: application/json

{
  "message": "Please give me a brief summary of my benefit plan in 2-3 sentences.\r\n"
}

###
POST http://localhost:59029/wca-chat
Content-Type: application/json

{
  "message": "Could you go into more detail on the first benefit plan please?"
}